name: Continuous Integration

on:
  push:
    branches-ignore:
      - main
    paths: 
      - '**.java'
  pull_request:
    branches-ignore:
      - main
    paths: 
      - '**.java'

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Maven package
        run: mvn -B clean package -DskipTests

      - name: Maven verify
        run: mvn clean verify
